import type { Metadata } from "next";

import "./globals.css";
import { ApolloClient, ApolloProvider, InMemoryCache } from "@apollo/client";
import Provider from "@/components/Provider";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
 title: "Create Next App",
 description: "Generated by create next app",
};

export default function RootLayout({
 children,
}: Readonly<{
 children: React.ReactNode;
}>) {
 return (
  <html lang="en">
   <Provider>
    <body>
     {children}
     <Toaster />
    </body>
   </Provider>
  </html>
 );
}
